// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const getUserByName = `-- name: GetUserByName :one
SELECT pass_hash, user_id FROM creds WHERE username = $1
`

type GetUserByNameRow struct {
	PassHash string
	UserID   uuid.UUID
}

func (q *Queries) GetUserByName(ctx context.Context, username string) (GetUserByNameRow, error) {
	row := q.db.QueryRow(ctx, getUserByName, username)
	var i GetUserByNameRow
	err := row.Scan(&i.PassHash, &i.UserID)
	return i, err
}

const registerNewUser = `-- name: RegisterNewUser :one
INSERT INTO creds (username, pass_hash)
VALUES ( $1, $2 )
RETURNING user_id
`

type RegisterNewUserParams struct {
	Username string
	PassHash string
}

func (q *Queries) RegisterNewUser(ctx context.Context, arg RegisterNewUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, registerNewUser, arg.Username, arg.PassHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :exec
UPDATE creds 
SET refresh_token_hash = $2
WHERE user_id = $1
`

type UpdateRefreshTokenParams struct {
	UserID           uuid.UUID
	RefreshTokenHash []byte
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, updateRefreshToken, arg.UserID, arg.RefreshTokenHash)
	return err
}
