// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package queries

import (
	"context"
)

const registerNewUser = `-- name: RegisterNewUser :exec
INSERT INTO creds (username, pass_hash)
VALUES ( $1, $2 )
`

type RegisterNewUserParams struct {
	Username string
	PassHash string
}

func (q *Queries) RegisterNewUser(ctx context.Context, arg RegisterNewUserParams) error {
	_, err := q.db.Exec(ctx, registerNewUser, arg.Username, arg.PassHash)
	return err
}
