// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard.sql

package queries

import (
	"context"
)

const fetchUserTier = `-- name: FetchUserTier :one
SELECT tier FROM tiers
WHERE $1 BETWEEN min_karma AND max_karma
`

func (q *Queries) FetchUserTier(ctx context.Context, minKarma int32) (string, error) {
	row := q.db.QueryRow(ctx, fetchUserTier, minKarma)
	var tier string
	err := row.Scan(&tier)
	return tier, err
}
