// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BuildingTypes string

const (
	BuildingTypesDefense   BuildingTypes = "defense"
	BuildingTypesStorage   BuildingTypes = "storage"
	BuildingTypesCollector BuildingTypes = "collector"
)

func (e *BuildingTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BuildingTypes(s)
	case string:
		*e = BuildingTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for BuildingTypes: %T", src)
	}
	return nil
}

type NullBuildingTypes struct {
	BuildingTypes BuildingTypes
	Valid         bool // Valid is true if BuildingTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBuildingTypes) Scan(value interface{}) error {
	if value == nil {
		ns.BuildingTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BuildingTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBuildingTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BuildingTypes), nil
}

type AttackHistory struct {
	AttackID              int64
	AttackerID            pgtype.UUID
	DefenderID            pgtype.UUID
	AttackTimestamp       pgtype.Timestamptz
	AttackEvents          []byte
	KarmaGained           int16
	DestructionPercentage int16
}

type BuildingsMasterTable struct {
	BuildingID    int16
	BuildingType  BuildingTypes
	BuildingName  string
	BuildingLevel int16
	Hp            int16
	TileCount     int16
	UpgradeCost   int32
	BuildingDesc  pgtype.Text
	UnlockLevel   int16
	UpgradeTime   int32
}

type Collector struct {
	BuildingID      int16
	ProductionRate  int32
	StorageCapacity int32
}

type Cred struct {
	UserID    uuid.UUID
	Username  string
	PassHash  string
	CreatedAt pgtype.Timestamptz
	IsDeleted bool
}

type Defense struct {
	BuildingID   int16
	DefenseRange int16
	Dps          int16
}

type Mercenary struct {
	MercenaryID    int16
	MercenaryName  string
	MercenaryLevel int16
	Hp             int16
	Dps            int16
	HousingSpace   int16
	MovementSpeed  int16
	MercenaryDesc  pgtype.Text
	UnlockLevel    int16
	MercenaryRange int16
}

type ResidenceProperty struct {
	UserID            uuid.UUID
	ResidenceLevel    int16
	Gems              int32
	Oil               int32
	OilLastCollected  pgtype.Timestamptz
	GemsLastCollected pgtype.Timestamptz
}

type Storage struct {
	BuildingID      int16
	StorageCapacity int32
}

type Tier struct {
	Tier     string
	MinKarma int32
	MaxKarma int32
}

type UserArmy struct {
	UserID      uuid.UUID
	MercenaryID int16
	Count       int16
}

type UserStat struct {
	UserID        uuid.UUID
	TotalAttacks  int32
	AttacksWon    int32
	TotalDefenses int32
	DefensesWon   int32
	Karma         int32
	OilLooted     int64
}

type VillageLayout struct {
	UserID                     uuid.UUID
	GlobalID                   int64
	TypeID                     int16
	XCoordinate                int16
	YCoordinate                int16
	UpgradeCompletionTimestamp pgtype.Timestamptz
}
