// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: army.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserArmy = `-- name: DeleteUserArmy :exec
DELETE FROM user_army 
WHERE user_id = $1
`

func (q *Queries) DeleteUserArmy(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserArmy, userID)
	return err
}

const getUserArmy = `-- name: GetUserArmy :many
SELECT mercenary_id, count 
FROM user_army 
WHERE user_army.user_id = $1
ORDER BY mercenary_id ASC
`

type GetUserArmyRow struct {
	MercenaryID int16 `json:"mercenary_id"`
	Count       int16 `json:"count"`
}

func (q *Queries) GetUserArmy(ctx context.Context, userID uuid.UUID) ([]GetUserArmyRow, error) {
	rows, err := q.db.Query(ctx, getUserArmy, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserArmyRow
	for rows.Next() {
		var i GetUserArmyRow
		if err := rows.Scan(&i.MercenaryID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserArmyCapacity = `-- name: GetUserArmyCapacity :one
WITH UserMercCamps AS (
    SELECT building_id FROM 
    village_layout JOIN buildings_master_table ON village_layout.type_id = buildings_master_table.building_id
    WHERE building_name = 'Mercenary Camp' AND user_id = $1
)
SELECT SUM(storage_capacity) ::SMALLINT AS capacity FROM
storages s JOIN UserMercCamps u ON s.building_id = u.building_id
`

func (q *Queries) GetUserArmyCapacity(ctx context.Context, userID uuid.UUID) (int16, error) {
	row := q.db.QueryRow(ctx, getUserArmyCapacity, userID)
	var capacity int16
	err := row.Scan(&capacity)
	return capacity, err
}

const insertArmyRow = `-- name: InsertArmyRow :exec
INSERT INTO user_army (user_id, mercenary_id, count)
VALUES ($1, $2, $3)
`

type InsertArmyRowParams struct {
	UserID      uuid.UUID `json:"user_id"`
	MercenaryID int16     `json:"mercenary_id"`
	Count       int16     `json:"count"`
}

func (q *Queries) InsertArmyRow(ctx context.Context, arg InsertArmyRowParams) error {
	_, err := q.db.Exec(ctx, insertArmyRow, arg.UserID, arg.MercenaryID, arg.Count)
	return err
}
