// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: battle.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getDefenderNameKarma = `-- name: GetDefenderNameKarma :one
SELECT username, karma FROM
creds JOIN user_stats 
ON creds.user_id = user_stats.user_id 
WHERE creds.user_id = $1
`

type GetDefenderNameKarmaRow struct {
	Username string `json:"username"`
	Karma    int32  `json:"karma"`
}

func (q *Queries) GetDefenderNameKarma(ctx context.Context, userID uuid.UUID) (GetDefenderNameKarmaRow, error) {
	row := q.db.QueryRow(ctx, getDefenderNameKarma, userID)
	var i GetDefenderNameKarmaRow
	err := row.Scan(&i.Username, &i.Karma)
	return i, err
}

const getDefenderUID = `-- name: GetDefenderUID :one
SELECT attacking_on FROM residence_properties
WHERE user_id = $1
`

func (q *Queries) GetDefenderUID(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDefenderUID, userID)
	var attacking_on uuid.UUID
	err := row.Scan(&attacking_on)
	return attacking_on, err
}

const getDefenderVillageLayout = `-- name: GetDefenderVillageLayout :many
SELECT type_id, x_coordinate, y_coordinate FROM
village_layout WHERE user_id = $1
`

type GetDefenderVillageLayoutRow struct {
	TypeID      int16 `json:"type_id"`
	XCoordinate int16 `json:"x_coordinate"`
	YCoordinate int16 `json:"y_coordinate"`
}

func (q *Queries) GetDefenderVillageLayout(ctx context.Context, userID uuid.UUID) ([]GetDefenderVillageLayoutRow, error) {
	rows, err := q.db.Query(ctx, getDefenderVillageLayout, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDefenderVillageLayoutRow
	for rows.Next() {
		var i GetDefenderVillageLayoutRow
		if err := rows.Scan(&i.TypeID, &i.XCoordinate, &i.YCoordinate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuitableOpponent = `-- name: GetSuitableOpponent :one
UPDATE residence_properties
SET under_attack = true
WHERE user_id = (
    SELECT user_stats.user_id FROM
    user_stats JOIN residence_properties ON user_stats.user_id = residence_properties.user_id
    WHERE 
    user_stats.user_id != $1
    AND karma BETWEEN $2 - 50 AND $2 + 50
    AND residence_level BETWEEN $3 - 1 AND $3 + 1
    AND under_attack = FALSE
    ORDER BY last_attacked ASC LIMIT 1
    FOR UPDATE SKIP LOCKED 
)
AND NOT EXISTS(
    SELECT 1 FROM residence_properties
    WHERE user_id = $1 AND in_battle = true
)
RETURNING user_id
`

type GetSuitableOpponentParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
}

func (q *Queries) GetSuitableOpponent(ctx context.Context, arg GetSuitableOpponentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSuitableOpponent, arg.UserID, arg.Column2, arg.Column3)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserInfoForMatchmaking = `-- name: GetUserInfoForMatchmaking :one
SELECT karma, residence_level, in_battle FROM 
user_stats JOIN residence_properties ON user_stats.user_id = residence_properties.user_id 
WHERE user_stats.user_id = $1
`

type GetUserInfoForMatchmakingRow struct {
	Karma          int32 `json:"karma"`
	ResidenceLevel int16 `json:"residence_level"`
	InBattle       bool  `json:"in_battle"`
}

func (q *Queries) GetUserInfoForMatchmaking(ctx context.Context, userID uuid.UUID) (GetUserInfoForMatchmakingRow, error) {
	row := q.db.QueryRow(ctx, getUserInfoForMatchmaking, userID)
	var i GetUserInfoForMatchmakingRow
	err := row.Scan(&i.Karma, &i.ResidenceLevel, &i.InBattle)
	return i, err
}

const setInBattle = `-- name: SetInBattle :exec
UPDATE residence_properties
SET in_battle = true, attacking_on = $2
WHERE user_id = $1
`

type SetInBattleParams struct {
	UserID      uuid.UUID `json:"user_id"`
	AttackingOn uuid.UUID `json:"attacking_on"`
}

func (q *Queries) SetInBattle(ctx context.Context, arg SetInBattleParams) error {
	_, err := q.db.Exec(ctx, setInBattle, arg.UserID, arg.AttackingOn)
	return err
}

const updateAttackerResidence = `-- name: UpdateAttackerResidence :exec
UPDATE residence_properties SET 
in_battle = FALSE, oil = oil + $1,
attacking_on = $2
WHERE user_id = $2
`

type UpdateAttackerResidenceParams struct {
	Oil         int32     `json:"oil"`
	AttackingOn uuid.UUID `json:"attacking_on"`
}

func (q *Queries) UpdateAttackerResidence(ctx context.Context, arg UpdateAttackerResidenceParams) error {
	_, err := q.db.Exec(ctx, updateAttackerResidence, arg.Oil, arg.AttackingOn)
	return err
}

const updateAttackerStats = `-- name: UpdateAttackerStats :exec
UPDATE user_stats SET
total_attacks = total_attacks + 1,
attacks_won = attacks_won + $2,
karma = karma + $3,
oil_looted = oil_looted + $4
WHERE user_id = $1
`

type UpdateAttackerStatsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	AttacksWon int32     `json:"attacks_won"`
	Karma      int32     `json:"karma"`
	OilLooted  int64     `json:"oil_looted"`
}

func (q *Queries) UpdateAttackerStats(ctx context.Context, arg UpdateAttackerStatsParams) error {
	_, err := q.db.Exec(ctx, updateAttackerStats,
		arg.UserID,
		arg.AttacksWon,
		arg.Karma,
		arg.OilLooted,
	)
	return err
}

const updateDefenderResidence = `-- name: UpdateDefenderResidence :exec
UPDATE residence_properties SET
under_attack = FALSE,
last_attacked = CURRENT_TIMESTAMP
WHERE user_id = $1
`

func (q *Queries) UpdateDefenderResidence(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateDefenderResidence, userID)
	return err
}

const updateDefenderStats = `-- name: UpdateDefenderStats :exec
UPDATE user_stats SET
total_defenses = total_defenses + 1,
defenses_won = defenses_won + $2,
karma = karma + $3
WHERE user_id = $1
`

type UpdateDefenderStatsParams struct {
	UserID      uuid.UUID `json:"user_id"`
	DefensesWon int32     `json:"defenses_won"`
	Karma       int32     `json:"karma"`
}

func (q *Queries) UpdateDefenderStats(ctx context.Context, arg UpdateDefenderStatsParams) error {
	_, err := q.db.Exec(ctx, updateDefenderStats, arg.UserID, arg.DefensesWon, arg.Karma)
	return err
}
