// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: battle.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getSuitableOpponent = `-- name: GetSuitableOpponent :one
UPDATE residence_properties
SET under_attack = true
WHERE user_id = (
    SELECT user_stats.user_id FROM
    user_stats JOIN residence_properties ON user_stats.user_id = residence_properties.user_id
    WHERE 
    user_stats.user_id != $1
    AND karma BETWEEN $2 - 50 AND $2 + 50
    AND residence_level BETWEEN $3 - 1 AND $3 + 1
    AND under_attack = FALSE
    ORDER BY last_attacked ASC LIMIT 1
    FOR UPDATE SKIP LOCKED 
)
AND NOT EXISTS(
    SELECT 1 FROM residence_properties
    WHERE user_id = $1 AND in_battle = true
)
RETURNING user_id
`

type GetSuitableOpponentParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Column3 interface{} `json:"column_3"`
}

func (q *Queries) GetSuitableOpponent(ctx context.Context, arg GetSuitableOpponentParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getSuitableOpponent, arg.UserID, arg.Column2, arg.Column3)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getUserInfoForMatchmaking = `-- name: GetUserInfoForMatchmaking :one
SELECT karma, residence_level, in_battle FROM 
user_stats JOIN residence_properties ON user_stats.user_id = residence_properties.user_id 
WHERE user_stats.user_id = $1
`

type GetUserInfoForMatchmakingRow struct {
	Karma          int32 `json:"karma"`
	ResidenceLevel int16 `json:"residence_level"`
	InBattle       bool  `json:"in_battle"`
}

func (q *Queries) GetUserInfoForMatchmaking(ctx context.Context, userID uuid.UUID) (GetUserInfoForMatchmakingRow, error) {
	row := q.db.QueryRow(ctx, getUserInfoForMatchmaking, userID)
	var i GetUserInfoForMatchmakingRow
	err := row.Scan(&i.Karma, &i.ResidenceLevel, &i.InBattle)
	return i, err
}

const setInBattle = `-- name: SetInBattle :exec
UPDATE residence_properties
SET in_battle = true 
WHERE user_id = $1
`

func (q *Queries) SetInBattle(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setInBattle, userID)
	return err
}
