// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: load.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getResidenceInfo = `-- name: GetResidenceInfo :one
SELECT creds.username, residence_level, gems, oil, oil_last_collected, gems_last_collected
FROM creds JOIN residence_properties
ON creds.user_id = residence_properties.user_id
WHERE creds.user_id = $1
`

type GetResidenceInfoRow struct {
	Username          string    `json:"username"`
	ResidenceLevel    int16     `json:"residence_level"`
	Gems              int32     `json:"gems"`
	Oil               int32     `json:"oil"`
	OilLastCollected  time.Time `json:"oil_last_collected"`
	GemsLastCollected time.Time `json:"gems_last_collected"`
}

func (q *Queries) GetResidenceInfo(ctx context.Context, userID uuid.UUID) (GetResidenceInfoRow, error) {
	row := q.db.QueryRow(ctx, getResidenceInfo, userID)
	var i GetResidenceInfoRow
	err := row.Scan(
		&i.Username,
		&i.ResidenceLevel,
		&i.Gems,
		&i.Oil,
		&i.OilLastCollected,
		&i.GemsLastCollected,
	)
	return i, err
}

const getUserStats = `-- name: GetUserStats :one
SELECT total_attacks, attacks_won, total_defenses, defenses_won, karma, oil_looted
FROM user_stats
WHERE user_stats.user_id = $1
`

type GetUserStatsRow struct {
	TotalAttacks  int32 `json:"total_attacks"`
	AttacksWon    int32 `json:"attacks_won"`
	TotalDefenses int32 `json:"total_defenses"`
	DefensesWon   int32 `json:"defenses_won"`
	Karma         int32 `json:"karma"`
	OilLooted     int64 `json:"oil_looted"`
}

func (q *Queries) GetUserStats(ctx context.Context, userID uuid.UUID) (GetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, getUserStats, userID)
	var i GetUserStatsRow
	err := row.Scan(
		&i.TotalAttacks,
		&i.AttacksWon,
		&i.TotalDefenses,
		&i.DefensesWon,
		&i.Karma,
		&i.OilLooted,
	)
	return i, err
}

const getUserVillageLayout = `-- name: GetUserVillageLayout :many
SELECT global_id, type_id, x_coordinate, y_coordinate
FROM village_layout
WHERE village_layout.user_id = $1
ORDER BY village_layout.global_id ASC
`

type GetUserVillageLayoutRow struct {
	GlobalID    int64 `json:"global_id"`
	TypeID      int16 `json:"type_id"`
	XCoordinate int16 `json:"x_coordinate"`
	YCoordinate int16 `json:"y_coordinate"`
}

func (q *Queries) GetUserVillageLayout(ctx context.Context, userID uuid.UUID) ([]GetUserVillageLayoutRow, error) {
	rows, err := q.db.Query(ctx, getUserVillageLayout, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserVillageLayoutRow
	for rows.Next() {
		var i GetUserVillageLayoutRow
		if err := rows.Scan(
			&i.GlobalID,
			&i.TypeID,
			&i.XCoordinate,
			&i.YCoordinate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
