// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const spendGems = `-- name: SpendGems :exec
UPDATE residence_properties
SET gems = gems - $2 WHERE user_id = $1
`

type SpendGemsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Gems   int32     `json:"gems"`
}

func (q *Queries) SpendGems(ctx context.Context, arg SpendGemsParams) error {
	_, err := q.db.Exec(ctx, spendGems, arg.UserID, arg.Gems)
	return err
}

const spendOil = `-- name: SpendOil :exec
UPDATE residence_properties
SET oil = oil - $2 WHERE user_id = $1
`

type SpendOilParams struct {
	UserID uuid.UUID `json:"user_id"`
	Oil    int32     `json:"oil"`
}

func (q *Queries) SpendOil(ctx context.Context, arg SpendOilParams) error {
	_, err := q.db.Exec(ctx, spendOil, arg.UserID, arg.Oil)
	return err
}
