// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getUserByName = `-- name: GetUserByName :one
SELECT pass_hash, user_id FROM creds WHERE username = $1
`

type GetUserByNameRow struct {
	PassHash string    `json:"pass_hash"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetUserByName(ctx context.Context, username string) (GetUserByNameRow, error) {
	row := q.db.QueryRow(ctx, getUserByName, username)
	var i GetUserByNameRow
	err := row.Scan(&i.PassHash, &i.UserID)
	return i, err
}

const getUserResidenceLevel = `-- name: GetUserResidenceLevel :one
SELECT residence_level FROM residence_properties WHERE user_id = $1
`

func (q *Queries) GetUserResidenceLevel(ctx context.Context, userID uuid.UUID) (int16, error) {
	row := q.db.QueryRow(ctx, getUserResidenceLevel, userID)
	var residence_level int16
	err := row.Scan(&residence_level)
	return residence_level, err
}

const getUserbyRTHash = `-- name: GetUserbyRTHash :one
SELECT user_id, refresh_token_expiry FROM creds WHERE refresh_token_hash = $1
`

type GetUserbyRTHashRow struct {
	UserID             uuid.UUID `json:"user_id"`
	RefreshTokenExpiry time.Time `json:"refresh_token_expiry"`
}

func (q *Queries) GetUserbyRTHash(ctx context.Context, refreshTokenHash []byte) (GetUserbyRTHashRow, error) {
	row := q.db.QueryRow(ctx, getUserbyRTHash, refreshTokenHash)
	var i GetUserbyRTHashRow
	err := row.Scan(&i.UserID, &i.RefreshTokenExpiry)
	return i, err
}

const registerNewUser = `-- name: RegisterNewUser :one
WITH new_user AS (
    INSERT INTO creds (username, pass_hash)
    VALUES ($1, $2)
    RETURNING user_id
),
new_stats AS (
    INSERT INTO user_stats (user_id)
    SELECT user_id FROM new_user
),
new_residence AS (
    INSERT INTO residence_properties (user_id, residence_level, gems, oil)
    SELECT user_id, 1, 50, 1000 FROM new_user
)
INSERT INTO village_layout (user_id, type_id, x_coordinate, y_coordinate)
SELECT user_id, v.type_id, v.x, v.y
FROM new_user
CROSS JOIN (
    VALUES
        (1::SMALLINT,  15::SMALLINT, 15::SMALLINT), 
        (5::SMALLINT,  15::SMALLINT, 25::SMALLINT), 
        (9::SMALLINT,  25::SMALLINT, 15::SMALLINT), 
        (13::SMALLINT, 20::SMALLINT, 25::SMALLINT)  
) AS v(type_id, x, y)
RETURNING user_id
`

type RegisterNewUserParams struct {
	Username string `json:"username"`
	PassHash string `json:"pass_hash"`
}

func (q *Queries) RegisterNewUser(ctx context.Context, arg RegisterNewUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, registerNewUser, arg.Username, arg.PassHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const updateRefreshToken = `-- name: UpdateRefreshToken :exec
UPDATE creds 
SET 
refresh_token_hash = $2,
refresh_token_expiry = $3
WHERE user_id = $1
`

type UpdateRefreshTokenParams struct {
	UserID             uuid.UUID `json:"user_id"`
	RefreshTokenHash   []byte    `json:"refresh_token_hash"`
	RefreshTokenExpiry time.Time `json:"refresh_token_expiry"`
}

func (q *Queries) UpdateRefreshToken(ctx context.Context, arg UpdateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, updateRefreshToken, arg.UserID, arg.RefreshTokenHash, arg.RefreshTokenExpiry)
	return err
}
