// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const isBaseUnderAttack = `-- name: IsBaseUnderAttack :one
SELECT under_attack FROM residence_properties WHERE user_id = $1
`

func (q *Queries) IsBaseUnderAttack(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isBaseUnderAttack, userID)
	var under_attack bool
	err := row.Scan(&under_attack)
	return under_attack, err
}
