// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config.sql

package db

import (
	"context"
)

const buildings = `-- name: Buildings :many
SELECT building_id, building_type, building_name, building_level, hp, tile_count, upgrade_cost, building_desc, unlock_level, upgrade_time FROM buildings_master_table ORDER BY building_id ASC
`

func (q *Queries) Buildings(ctx context.Context) ([]BuildingsMasterTable, error) {
	rows, err := q.db.Query(ctx, buildings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BuildingsMasterTable
	for rows.Next() {
		var i BuildingsMasterTable
		if err := rows.Scan(
			&i.BuildingID,
			&i.BuildingType,
			&i.BuildingName,
			&i.BuildingLevel,
			&i.Hp,
			&i.TileCount,
			&i.UpgradeCost,
			&i.BuildingDesc,
			&i.UnlockLevel,
			&i.UpgradeTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectors = `-- name: Collectors :many
SELECT building_id, production_rate, storage_capacity FROM collectors ORDER BY building_id ASC
`

func (q *Queries) Collectors(ctx context.Context) ([]Collector, error) {
	rows, err := q.db.Query(ctx, collectors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collector
	for rows.Next() {
		var i Collector
		if err := rows.Scan(&i.BuildingID, &i.ProductionRate, &i.StorageCapacity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const defenses = `-- name: Defenses :many
SELECT building_id, defense_range, dps, attack_rate FROM defenses ORDER BY building_id ASC
`

func (q *Queries) Defenses(ctx context.Context) ([]Defense, error) {
	rows, err := q.db.Query(ctx, defenses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Defense
	for rows.Next() {
		var i Defense
		if err := rows.Scan(
			&i.BuildingID,
			&i.DefenseRange,
			&i.Dps,
			&i.AttackRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mercs = `-- name: Mercs :many
SELECT mercenary_id, mercenary_name, mercenary_level, hp, dps, housing_space, movement_speed, mercenary_desc, unlock_level, mercenary_range FROM mercenaries ORDER BY mercenary_id ASC
`

func (q *Queries) Mercs(ctx context.Context) ([]Mercenary, error) {
	rows, err := q.db.Query(ctx, mercs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mercenary
	for rows.Next() {
		var i Mercenary
		if err := rows.Scan(
			&i.MercenaryID,
			&i.MercenaryName,
			&i.MercenaryLevel,
			&i.Hp,
			&i.Dps,
			&i.HousingSpace,
			&i.MovementSpeed,
			&i.MercenaryDesc,
			&i.UnlockLevel,
			&i.MercenaryRange,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storages = `-- name: Storages :many
SELECT building_id, storage_capacity FROM storages ORDER BY building_id ASC
`

func (q *Queries) Storages(ctx context.Context) ([]Storage, error) {
	rows, err := q.db.Query(ctx, storages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Storage
	for rows.Next() {
		var i Storage
		if err := rows.Scan(&i.BuildingID, &i.StorageCapacity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
