// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: layout.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addBuilding = `-- name: AddBuilding :exec
INSERT INTO village_layout (user_id, type_id, x_coordinate, y_coordinate)
VALUES ($1, $2, $3, $4)
`

type AddBuildingParams struct {
	UserID      uuid.UUID `json:"user_id"`
	TypeID      int16     `json:"type_id"`
	XCoordinate int16     `json:"x_coordinate"`
	YCoordinate int16     `json:"y_coordinate"`
}

func (q *Queries) AddBuilding(ctx context.Context, arg AddBuildingParams) error {
	_, err := q.db.Exec(ctx, addBuilding,
		arg.UserID,
		arg.TypeID,
		arg.XCoordinate,
		arg.YCoordinate,
	)
	return err
}

const getBuildingType = `-- name: GetBuildingType :one
SELECT type_id FROM village_layout WHERE global_id = $1 AND user_id = $2
`

type GetBuildingTypeParams struct {
	GlobalID int64     `json:"global_id"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) GetBuildingType(ctx context.Context, arg GetBuildingTypeParams) (int16, error) {
	row := q.db.QueryRow(ctx, getBuildingType, arg.GlobalID, arg.UserID)
	var type_id int16
	err := row.Scan(&type_id)
	return type_id, err
}

const getOccupiedPositions = `-- name: GetOccupiedPositions :many
SELECT tile_count, x_coordinate, y_coordinate FROM village_layout JOIN buildings_master_table
ON village_layout.type_id = buildings_master_table.building_id
WHERE user_id = $1 AND global_id != $2
`

type GetOccupiedPositionsParams struct {
	UserID   uuid.UUID `json:"user_id"`
	GlobalID int64     `json:"global_id"`
}

type GetOccupiedPositionsRow struct {
	TileCount   int16 `json:"tile_count"`
	XCoordinate int16 `json:"x_coordinate"`
	YCoordinate int16 `json:"y_coordinate"`
}

func (q *Queries) GetOccupiedPositions(ctx context.Context, arg GetOccupiedPositionsParams) ([]GetOccupiedPositionsRow, error) {
	rows, err := q.db.Query(ctx, getOccupiedPositions, arg.UserID, arg.GlobalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOccupiedPositionsRow
	for rows.Next() {
		var i GetOccupiedPositionsRow
		if err := rows.Scan(&i.TileCount, &i.XCoordinate, &i.YCoordinate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserResidenceLvlandResources = `-- name: GetUserResidenceLvlandResources :one
SELECT residence_level, oil, gems FROM residence_properties WHERE user_id = $1
`

type GetUserResidenceLvlandResourcesRow struct {
	ResidenceLevel int16 `json:"residence_level"`
	Oil            int32 `json:"oil"`
	Gems           int32 `json:"gems"`
}

func (q *Queries) GetUserResidenceLvlandResources(ctx context.Context, userID uuid.UUID) (GetUserResidenceLvlandResourcesRow, error) {
	row := q.db.QueryRow(ctx, getUserResidenceLvlandResources, userID)
	var i GetUserResidenceLvlandResourcesRow
	err := row.Scan(&i.ResidenceLevel, &i.Oil, &i.Gems)
	return i, err
}

const updateBuildingPosition = `-- name: UpdateBuildingPosition :exec
UPDATE village_layout 
SET x_coordinate = $1, y_coordinate = $2
WHERE global_id = $3
`

type UpdateBuildingPositionParams struct {
	XCoordinate int16 `json:"x_coordinate"`
	YCoordinate int16 `json:"y_coordinate"`
	GlobalID    int64 `json:"global_id"`
}

func (q *Queries) UpdateBuildingPosition(ctx context.Context, arg UpdateBuildingPositionParams) error {
	_, err := q.db.Exec(ctx, updateBuildingPosition, arg.XCoordinate, arg.YCoordinate, arg.GlobalID)
	return err
}

const upgradeBuilding = `-- name: UpgradeBuilding :exec
UPDATE village_layout
SET type_id = type_id + 1 WHERE global_id = $1
`

func (q *Queries) UpgradeBuilding(ctx context.Context, globalID int64) error {
	_, err := q.db.Exec(ctx, upgradeBuilding, globalID)
	return err
}
