// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const leaderboard = `-- name: Leaderboard :many
SELECT 
DENSE_RANK() OVER(ORDER BY karma DESC) AS rank,
creds.user_id, username, attacks_won, defenses_won, karma
FROM creds JOIN user_stats ON creds.user_id = user_stats.user_id
LIMIT 100
`

type LeaderboardRow struct {
	Rank        int64     `json:"rank"`
	UserID      uuid.UUID `json:"user_id"`
	Username    string    `json:"username"`
	AttacksWon  int32     `json:"attacks_won"`
	DefensesWon int32     `json:"defenses_won"`
	Karma       int32     `json:"karma"`
}

func (q *Queries) Leaderboard(ctx context.Context) ([]LeaderboardRow, error) {
	rows, err := q.db.Query(ctx, leaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeaderboardRow
	for rows.Next() {
		var i LeaderboardRow
		if err := rows.Scan(
			&i.Rank,
			&i.UserID,
			&i.Username,
			&i.AttacksWon,
			&i.DefensesWon,
			&i.Karma,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userPercentile = `-- name: UserPercentile :one
SELECT 
ROUND(PERCENT_RANK() OVER (ORDER BY karma ASC) * 100, 2) AS percentile
FROM user_stats WHERE user_id = $1
`

func (q *Queries) UserPercentile(ctx context.Context, userID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, userPercentile, userID)
	var percentile float64
	err := row.Scan(&percentile)
	return percentile, err
}

const userTier = `-- name: UserTier :one
SELECT tier FROM tiers
WHERE $1 BETWEEN min_karma AND max_karma
`

func (q *Queries) UserTier(ctx context.Context, minKarma int32) (string, error) {
	row := q.db.QueryRow(ctx, userTier, minKarma)
	var tier string
	err := row.Scan(&tier)
	return tier, err
}
